name: secret-ci

on: 
  workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true
jobs:
  test_secret_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret
        env:
          MY_SECRET: ${{ secrets.MY_KEY }}
        run: |
          echo "The secret is available."
          echo "Length: ${#MY_SECRET}"
  
